apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - ap-south-1a
  - ap-south-1b
  - ap-south-1c
metadata:
  name: workshop-k8s-cluster
  region: ap-south-1
  version: "1.29"
iam:
  withOIDC: true
vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
addons:
  - name: vpc-cni
    version: 1.16.0
    configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true"}'
    resolveConflicts: overwrite
managedNodeGroups:
  - name: default
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    instanceType: g5.2xlarge
    privateNetworking: true
    updateConfig:
      maxUnavailablePercentage: 50
    labels:
      workshop-default: "yes"
